### ISSUE TITLE
Unexpected behavior for production deployment

### ISSUE THREAD

**Issue by ashishagin** [vercel-labs/blue-green#5]
Hi Vercel Team,

Thank you for providing this template! We've gone through the [official detailed guide](https://vercel.com/guides/blue_green_deployments_on_vercel) and got an unexpected behavior. Hopefully you'll be able to bring a little more clarity to it.

**Here are the steps we've performed:**

- Deployed the project from template
- Activated Skew Protection (set it to 12 hours just in case)
- Activated Deployment Protection Bypass
- Disabled Auto-Assign Custom Production Domains
- Created an edge config with the given structure and assigned it to the project

**After configuring the template:**
- Made 1st commit (blue)
- Got a new staged deployment for blue (name: kpta06k8s, deployment_id: 3hLGq19X25VdZJRJb4GgrZKj8uZB)
- Promoted it to production (let's assume it's our current production version now), assigned domain: bg-deployment.vercel.app
- Made 2nd commit (green)
- Got a new staged deployment for green (name: dvlhqub4s, deployment_id: APj98qJsXj7KkUVZ6uNerj2it18o)
- Left it in a staged (let's assume it's our next production version, which we'd like to test on a limited number of users).

![image](https://github.com/vercel-labs/blue-green/assets/43253316/34e88e5a-3a18-4887-866c-c7ddd08b327b)

**Finally, we've made changes to edge config:**
```
{
  "blue-green-configuration": {
    "deploymentDomainBlue": "bg-deployment-kpta06k8s-xxx.vercel.app",
    "deploymentDomainGreen": "bg-deployment-dvlhqub4s-xxx.vercel.app",
    "trafficGreenPercent": 50
  }
}
```

Now, according to the guide, that should be it - green deployment is still staged, but we've already started splitting the traffic.

**Expected result:**
- We continue working with default domain for current production: bg-deployment.vercel.app
- We have both deployments working

**Observed result:**
- Blue deployment continues working fine under https://bg-deployment.vercel.app/

![image](https://github.com/vercel-labs/blue-green/assets/43253316/1809f6ae-f851-4475-9a0f-e839687ae58b)
- Green deployment loads the page, but fails to load static assets:

![image](https://github.com/vercel-labs/blue-green/assets/43253316/3c94ea26-ed44-43bd-8ff7-81ef3424c319)
![image](https://github.com/vercel-labs/blue-green/assets/43253316/83e93a8f-d484-4b0f-a020-ac281540eefb)

**And the most curios thing is**
- If we go to staged green deployment dvlhqub4s and access it under https://bg-deployment-xxx.vercel.app/
- Both blue and green will work:
![image](https://github.com/vercel-labs/blue-green/assets/43253316/563634a1-812a-4f36-a18d-e617925e804e)
![image](https://github.com/vercel-labs/blue-green/assets/43253316/3f043421-666d-41f6-af9a-dc19b1b8660c)

**What we've also learned**
- If we will go and promote green deployment to be active production
- Both blue and green will start working under  https://bg-deployment.vercel.app/ (though on a previous step they did not work)
- Good! but it contradicts with an idea of testing green deployment first, and only after that making it active

**PS:**
- We've checked the latest commit from May 15th (commit id: 5d4ce15802861759bb1c60aebb896b56b70de43c)
- With all the same steps above, green staged deployment stopped serving blue-green at all (bc of the new condition added)

We will appreciate you can clarify this behavior and let us know how to make this schema work like it is described in the guide, or let us know if there is smth that is slipping away from us.

Thanks in advance!
Alex

**Comment by dominiksipowicz** [comment]
The issue was probably the skew protection window expired and it should return 404 in that case. The other possibility is that the project is set up with many production domains assigned to the deployment which should be fixed in the latest PR here: https://github.com/vercel-labs/blue-green/pull/6

**Comment by ashishagin** [comment]
@dominiksipowicz thank you for your reply!  Unfortunately, after the fix in #6  the issue persists. This condition

``` 
// We only run blue-green deployments when accessing from production urls
  if (req.nextUrl.hostname !== process.env.VERCEL_PROJECT_PRODUCTION_URL) {
    return NextResponse.next();
  }
```
does not seem to be a root cause for the issue, 404 for part of the static assets is being observed with and without it. 

Please find the recording capturing the full setup made from scratch on the enterprise plan: 

https://github.com/vercel-labs/blue-green/assets/43253316/4a03929c-b8e3-449e-8e65-08a4963725fc

I have a guess this particular behavior is not directly caused by the template middleware itself. It looks more like a platform-related issue (either smth with skew protection or smth with domain routing rules, bc the issue happens outside of the middleware)

Appreciate you'll check the repro steps and confirm if issue exists + recommend on how to make provided setup work.

Thanks in advance!

**Comment by dominiksipowicz** [comment]
@ashishagin I watched the whole video. Thank you for sharking this. Can you promote green to production and test again please. From what I see this is the only difference how I was testing it.

**Comment by dominiksipowicz** [comment]
@ashishagin actually, can you pull the latest code and test it with changes from the https://github.com/vercel-labs/blue-green/pull/7

**Comment by ashishagin** [comment]
@dominiksipowicz I've checked the latest version, let me share results:

- Running from blue still gives the same results (404 for static assets)
- Promoting to green and running from green works

I think now we've got to the point where I can ask **a short specific question:** 

Is it possible to run blue-green approach from blue current deployment without promoting green immediately after it has been created?

**Let me explain:**

We need green deployment to be considered as a "candidate", smth we want to accept/approve before making it "current" live version. Having this "direct" approach would give us a flexibility to manipulate staged (candidate) deployments without touching the current live version:

- Promote (in case its approved)
- Delete (in case it was not approved or has some other blocking issue)
- Perform another deployment, let's say green2 (in case we need a hotfix)

Having "reverse" approach, when we immediately making a "candidate" to be live version, in turn, has impact on the following aspects: 

- Maintainability: Making rollbacks and promotions back and forth (in case we did not get the approval)
- Reliability: Putting blue (approved and stable) deployment to the risk, bc green deployment makes the orchestration
- Costs (for our case): As we are sending the whole traffic through the green deployment and get additional hits to Vercel platform (1 original + 1 override), while planning to have "candidate" green traffic not to exceed 15% of the whole.

**As a side note**:

The [ detailed guide ](https://vercel.com/guides/blue_green_deployments_on_vercel) seems to be explaining the "direct" approach, as steps "Start Splitting Traffic Upon New Staged Deployment" and "Promote a Build After Approval' are spaced apart.

**Comment by dominiksipowicz** [comment]
@ashishagin 
It works for me running from the blue and with green as "Production: Staged". 
Could you please confirm:
1. The Edge Config points to the correct deployments.
2. The skew protection did not expire on both blue and green deployments.

In the screenshot below, I can confirm what I tested:
![CleanShot 2024-06-01 at 02 00 20@2x](https://github.com/vercel-labs/blue-green/assets/1570963/f7b4c418-bc01-4442-8b2a-47da75667f07)

**Comment by ashishagin** [comment]
@dominiksipowicz great news - now blue-green runs from blue smoothly.🔥It also started working for the previous versions of the template. 

Appreciate your help on this matter!
Alexey
